In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [4]:
data = pd.read_csv(
    r"C:\Users\durga\Downloads\Data Set For Task-20260526T161503Z-3-001\Data Set For Task\4) house Prediction Data Set.csv",
    sep=r"\s+"
)

In [5]:
columns = [
    "CRIM","ZN","INDUS","CHAS","NOX","RM","AGE",
    "DIS","RAD","TAX","PTRATIO","B","LSTAT","PRICE"
]

data.columns = columns
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
1,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
2,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
3,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
4,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222.0,18.7,394.12,5.21,28.7

In [6]:
data["PRICE_CLASS"] = data["PRICE"].apply(lambda x: 1 if x > data["PRICE"].median() else 0)
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE,PRICE_CLASS
0,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6,1
1,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7,1
2,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4,1
3,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2,1
4,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222.0,18.7,394.12,5.21,28.7,1

In [7]:
X = data.drop(["PRICE", "PRICE_CLASS"], axis=1)
y = data["PRICE_CLASS"]

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [10]:
y_pred = model.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8415841584158416
[[43 12]
 [ 4 42]]
              precision    recall  f1-score   support

           0       0.91      0.78      0.84        55
           1       0.78      0.91      0.84        46

    accuracy                           0.84       101
   macro avg       0.85      0.85      0.84       101
weighted avg       0.85      0.84      0.84       101

In [12]:
for k in range(1, 11):
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    print("K =", k, "Accuracy =", accuracy_score(y_test, pred))

K = 1 Accuracy = 0.801980198019802
K = 2 Accuracy = 0.7623762376237624
K = 3 Accuracy = 0.8415841584158416
K = 4 Accuracy = 0.7920792079207921
K = 5 Accuracy = 0.7722772277227723
K = 6 Accuracy = 0.7821782178217822
K = 7 Accuracy = 0.7821782178217822
K = 8 Accuracy = 0.7821782178217822
K = 9 Accuracy = 0.7920792079207921
K = 10 Accuracy = 0.7821782178217822